windowrule = match:class ^(steam)$, workspace 1
windowrule = match:class ^(vesktop)$, workspace 4
windowrule = match:class ^(spotify)$, workspace 5


windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(nm-connection-editor)$, size (monitor_w*0.35) (monitor_h*0.5)

windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size (monitor_w*0.35) (monitor_h*0.5)
windowrule = match:class ^(org\.pulseaudio\.pavucontrol)$, move 100%-w-1 25

windowrule = match:class ^(feh)$, float on
windowrule = match:class ^(feh)$, size (monitor_w*0.5) (monitor_h*0.5)
windowrule = match:class ^(feh)$, center on

windowrule = match:class ^(org.gnome.SystemMonitor)$, float on
windowrule = match:class ^(org.gnome.SystemMonitor)$, size (monitor_w*0.45) (monitor_h*0.75)
windowrule = match:class ^(org.gnome.SystemMonitor)$, center on

windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, size (monitor_w*0.45) (monitor_h*0.75)
windowrule = match:class ^(blueman-manager)$, center on

windowrule = match:class .*, suppress_event maximize

windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on

# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣤⣤⣤⡄⠀⠀⠀⠀⢠⣤⣤⣤⡄⠀⠀⠀⠀⢠⣤⣤⣤⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⣀⣀⣀⣀⣿⣿⣿⣿⣀⣀⣀⣀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
# ⣿⠀⠿⠿⠀⣿⡇⠀⠤⠤⣼⣿⡇⠀⣿⣿⣿⡇⠀⢸⣿⣿⡇⠀⣤⣤⠀⢹⣿⠀⣿⡀⠹⡿⠁⣰⣿⠀⠀⠤⠤⣼⣿⠀⢠⣤⡄⢸⡟⠀⠤⠤⣽⣿
# ⣿⠀⣤⣤⠀⣿⡇⠀⠒⠒⢻⣿⡇⠀⠛⠛⣿⡇⠀⠘⠛⢻⡇⠀⠛⠛⠀⣸⣿⠀⣿⣿⡀⠀⣰⣿⣿⠀⠀⠒⠒⢻⣿⠀⢠⣤⡄⢹⣟⠒⠒⠂⢈⣿
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
# ⣿⣷⣄⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣸⢀⡀⢀⡀⣧⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣠⣾⣿
# ⣿⣿⣿⣷⣶⣶⣶⣶⣶⣶⣖⣒⣒⣒⣒⣒⣲⣖⣒⣒⣒⣒⣒⣯⣜⢡⡌⣃⣼⣒⣒⣒⣒⣒⣲⣖⣒⣒⣒⣒⣒⣲⣶⣶⣶⣶⣶⣶⣾⣿⣿⣿
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⢸⣷⣤⣾⡇⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠛⠛⠛⠃⠀⠀⠀⠀⠘⠛⠛⠛⠃⠀⠀⠀⠀⠘⠛⠛⠛⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿


windowrule = match:class ^(steam_app_553850)$, match:title ^(HELLDIVERS™ 2)$, workspace 1
windowrule = match:class ^(steam_app_553850)$, match:title ^(HELLDIVERS™ 2)$, border_size 0
windowrule = match:class ^(steam_app_553850)$, match:title ^(HELLDIVERS™ 2)$, float on
windowrule = match:class ^(steam_app_553850)$, match:title ^(HELLDIVERS™ 2)$, size 2560 1440
windowrule = match:class ^(steam_app_553850)$, match:title ^(HELLDIVERS™ 2)$, move 100%-w-1 25